import { signInUserStateReset } from "../slices/SignIn";
import { addKeyStateReset } from "../slices/addKey";
import { conditionsStateReset } from "../slices/appConditions";
import { changePasswordStateReset } from "../slices/changePassword";
import { contactUsStateReset } from "../slices/contactUs";
import { forgotPasswordStateReset } from "../slices/forgotPassword";
import { getCollectionCodeStateReset } from "../slices/getCollectionCode";
import { getKeyCatalogsStateReset } from "../slices/getKeyCatalog";
import { addKeyDetailStateReset } from "../slices/getKeyDetail";
import { getKeyHostsStateReset } from "../slices/getKeyHosts";
import { getOwnHistoryStateReset } from "../slices/getOwnerHistory";
import { getPlansStateReset } from "../slices/getPlans";
import { hostProfileStateReset } from "../slices/hostProfile";
import { linkKeyRingStateReset } from "../slices/linkKeyRing";
import { logoutUserReset } from "../slices/logout";
import { notificationStateReset } from "../slices/notificationSetting";
import { notifyStateReset } from "../slices/notify";
import { ownerStateReset } from "../slices/owner";
import { getOwnProfileStateReset } from "../slices/profileDetail";
import { registerNewKeyStateReset } from "../slices/registerNewKey";
import { resendOtpStateReset } from "../slices/resendOtp";
import { resetPasswordStateReset } from "../slices/resetPassword";
import { setKeyValidityStateReset } from "../slices/setValidity";
import { unreadCountStateReset } from "../slices/unreadCount";
import { updateKeyStateReset } from "../slices/updateKey";
import { updateKeyStatusStateReset } from "../slices/updateKeyStatus";
import { updateProfileStateReset } from "../slices/updateProfile";
import { verifyOtpStateReset } from "../slices/verifyOtp";

export const reduxReset = () => (dispatch: any) => {
  dispatch(addKeyStateReset());
  dispatch(conditionsStateReset());
  dispatch(verifyOtpStateReset());
  dispatch(updateProfileStateReset());
  dispatch(updateKeyStatusStateReset());
  dispatch(updateKeyStateReset());
  dispatch(unreadCountStateReset());
  dispatch(signInUserStateReset());
  dispatch(setKeyValidityStateReset());
  dispatch(resetPasswordStateReset());
  dispatch(resendOtpStateReset());
  dispatch(registerNewKeyStateReset());
  dispatch(getOwnProfileStateReset());
  dispatch(ownerStateReset());
  dispatch(notifyStateReset());
  dispatch(notificationStateReset());
  dispatch(logoutUserReset());
  dispatch(linkKeyRingStateReset());
  dispatch(hostProfileStateReset());
  dispatch(getPlansStateReset());
  dispatch(getOwnHistoryStateReset());
  dispatch(getKeyHostsStateReset());
  dispatch(addKeyDetailStateReset());
  dispatch(getKeyCatalogsStateReset());
  dispatch(getCollectionCodeStateReset());
  dispatch(forgotPasswordStateReset());
  dispatch(contactUsStateReset());
  dispatch(changePasswordStateReset());
};
