interface CountryData {
    countryCode: string;
    currencyCode: string;
  }
  
export const countryMapping: { [countryName: string]: CountryData } = {
    'United States': { countryCode: 'US', currencyCode: 'USD' },
    'Canada': { countryCode: 'CA', currencyCode: 'CAD' },
    'Russia': { countryCode: 'RU', currencyCode: 'RUB' },
    'Kazakhstan': { countryCode: 'KZ', currencyCode: 'KZT' },
    'Egypt': { countryCode: 'EG', currencyCode: 'EGP' },
    'South Africa': { countryCode: 'ZA', currencyCode: 'ZAR' },
    'Greece': { countryCode: 'GR', currencyCode: 'EUR' },
    'Netherlands': { countryCode: 'NL', currencyCode: 'EUR' },
    'Belgium': { countryCode: 'BE', currencyCode: 'EUR' },
    'France': { countryCode: 'FR', currencyCode: 'EUR' },
    'Spain': { countryCode: 'ES', currencyCode: 'EUR' },
    'Australia': { countryCode: 'AU', currencyCode: 'AUD' },
    'Italy': { countryCode: 'IT', currencyCode: 'EUR' },
    'Switzerland': { countryCode: 'CH', currencyCode: 'CHF' },
    'United Kingdom': { countryCode: 'GB', currencyCode: 'GBP' },
    'Germany': { countryCode: 'DE', currencyCode: 'EUR' },
    'Peru': { countryCode: 'PE', currencyCode: 'PEN' },
    'Mexico': { countryCode: 'MX', currencyCode: 'MXN' },
    'Cuba': { countryCode: 'CU', currencyCode: 'CUP' },
    'Argentina': { countryCode: 'AR', currencyCode: 'ARS' },
    'Brazil': { countryCode: 'BR', currencyCode: 'BRL' },
    'Malaysia': { countryCode: 'MY', currencyCode: 'MYR' },
    'Indonesia': { countryCode: 'ID', currencyCode: 'IDR' },
    'Philippines': { countryCode: 'PH', currencyCode: 'PHP' },
    'New Zealand': { countryCode: 'NZ', currencyCode: 'NZD' },
    'Singapore': { countryCode: 'SG', currencyCode: 'SGD' },
    'Thailand': { countryCode: 'TH', currencyCode: 'THB' },
    'Japan': { countryCode: 'JP', currencyCode: 'JPY' },
    'South Korea': { countryCode: 'KR', currencyCode: 'KRW' },
    'Vietnam': { countryCode: 'VN', currencyCode: 'VND' },
    'China': { countryCode: 'CN', currencyCode: 'CNY' },
    'Turkey': { countryCode: 'TR', currencyCode: 'TRY' },
    'India': { countryCode: 'IN', currencyCode: 'INR' },
    'Pakistan': { countryCode: 'PK', currencyCode: 'PKR' },
    'Afghanistan': { countryCode: 'AF', currencyCode: 'AFN' },
    'Sri Lanka': { countryCode: 'LK', currencyCode: 'LKR' },
    'Myanmar': { countryCode: 'MM', currencyCode: 'MMK' },
    'Iran': { countryCode: 'IR', currencyCode: 'IRR' },
    'South Sudan': { countryCode: 'SS', currencyCode: 'SSP' },
    'Morocco': { countryCode: 'MA', currencyCode: 'MAD' },
    'Algeria': { countryCode: 'DZ', currencyCode: 'DZD' },
    'Tunisia': { countryCode: 'TN', currencyCode: 'TND' },
    'Libya': { countryCode: 'LY', currencyCode: 'LYD' },
    'Gambia': { countryCode: 'GM', currencyCode: 'GMD' },
    'Senegal': { countryCode: 'SN', currencyCode: 'XOF' },
    'Mauritania': { countryCode: 'MR', currencyCode: 'MRU' },
    'Madagascar': { countryCode: 'MG', currencyCode: 'MGA' },
    'Guinea': { countryCode: 'GN', currencyCode: 'GNF' },
    'Côte d\'Ivoire': { countryCode: 'CI', currencyCode: 'XOF' },
    'Burkina Faso': { countryCode: 'BF', currencyCode: 'XOF' },
    'Niger': { countryCode: 'NE', currencyCode: 'XOF' },
    'Togo': { countryCode: 'TG', currencyCode: 'XOF' },
    'Benin': { countryCode: 'BJ', currencyCode: 'XOF' },
    'Mauritius': { countryCode: 'MU', currencyCode: 'MUR' },
    'Liberia': { countryCode: 'LR', currencyCode: 'LRD' },
    'Sierra Leone': { countryCode: 'SL', currencyCode: 'SLL' },
    'Ghana': { countryCode: 'GH', currencyCode: 'GHS' },
    'Nigeria': { countryCode: 'NG', currencyCode: 'NGN' },
    'Chad': { countryCode: 'TD', currencyCode: 'XAF' },
    'Central African Republic': { countryCode: 'CF', currencyCode: 'XAF' },
    'Cameroon': { countryCode: 'CM', currencyCode: 'XAF' },
    'Cape Verde': { countryCode: 'CV', currencyCode: 'CVE' },
    'São Tomé and Príncipe': { countryCode: 'ST', currencyCode: 'STN' },
    'Equatorial Guinea': { countryCode: 'GQ', currencyCode: 'XAF' },
    'Gabon': { countryCode: 'GA', currencyCode: 'XAF' },
    'Congo': { countryCode: 'CG', currencyCode: 'XAF' },
    'Democratic Republic of the Congo': { countryCode: 'CD', currencyCode: 'CDF' },
    'Angola': { countryCode: 'AO', currencyCode: 'AOA' },
    'British Indian Ocean Territory': { countryCode: 'IO', currencyCode: 'USD' },
    'Seychelles': { countryCode: 'SC', currencyCode: 'SCR' },
    'Sudan': { countryCode: 'SD', currencyCode: 'SDG' },
    'Rwanda': { countryCode: 'RW', currencyCode: 'RWF' },
    'Ethiopia': { countryCode: 'ET', currencyCode: 'ETB' },
    'Somalia': { countryCode: 'SO', currencyCode: 'SOS' },
    'Djibouti': { countryCode: 'DJ', currencyCode: 'DJF' },
    'Kenya': { countryCode: 'KE', currencyCode: 'KES' },
    'Tanzania': { countryCode: 'TZ', currencyCode: 'TZS' },
    'Uganda': { countryCode: 'UG', currencyCode: 'UGX' },
    'Burundi': { countryCode: 'BI', currencyCode: 'BIF' },
    'Mozambique': { countryCode: 'MZ', currencyCode: 'MZN' },
    'Zambia': { countryCode: 'ZM', currencyCode: 'ZMW' },
    'Réunion': { countryCode: 'RE', currencyCode: 'EUR' },
    'Zimbabwe': { countryCode: 'ZW', currencyCode: 'ZWL' },
    'Namibia': { countryCode: 'NA', currencyCode: 'NAD' },
    'Malawi': { countryCode: 'MW', currencyCode: 'MWK' },
    'Lesotho': { countryCode: 'LS', currencyCode: 'LSL' },
    'Botswana': { countryCode: 'BW', currencyCode: 'BWP' },
    'Eswatini': { countryCode: 'SZ', currencyCode: 'SZL' },
    'Comoros': { countryCode: 'KM', currencyCode: 'KMF' },
    'Saint Helena': { countryCode: 'SH', currencyCode: 'SHP' },
    'Eritrea': { countryCode: 'ER', currencyCode: 'ERN' },
    'Aruba': { countryCode: 'AW', currencyCode: 'AWG' },
    'Faroe Islands': { countryCode: 'FO', currencyCode: 'DKK' },
    'Greenland': { countryCode: 'GL', currencyCode: 'DKK' },
    'Gibraltar': { countryCode: 'GI', currencyCode: 'GIP' },
    'Portugal': { countryCode: 'PT', currencyCode: 'EUR' },
    'Luxembourg': { countryCode: 'LU', currencyCode: 'EUR' },
    'Ireland': { countryCode: 'IE', currencyCode: 'EUR' },
    'Iceland': { countryCode: 'IS', currencyCode: 'ISK' },
    'Albania': { countryCode: 'AL', currencyCode: 'ALL' },
    'Malta': { countryCode: 'MT', currencyCode: 'EUR' },
    'Cyprus': { countryCode: 'CY', currencyCode: 'EUR' },
    'Finland': { countryCode: 'FI', currencyCode: 'EUR' },
    'Bulgaria': { countryCode: 'BG', currencyCode: 'BGN' },
    'Lithuania': { countryCode: 'LT', currencyCode: 'EUR' },
    'Latvia': { countryCode: 'LV', currencyCode: 'EUR' },
    'Estonia': { countryCode: 'EE', currencyCode: 'EUR' },
    'Moldova': { countryCode: 'MD', currencyCode: 'MDL' },
    'Armenia': { countryCode: 'AM', currencyCode: 'AMD' },
    'Belarus': { countryCode: 'BY', currencyCode: 'BYN' },
    'Andorra': { countryCode: 'AD', currencyCode: 'EUR' },
    'Monaco': { countryCode: 'MC', currencyCode: 'EUR' },
    'San Marino': { countryCode: 'SM', currencyCode: 'EUR' },
    'Vatican City': { countryCode: 'VA', currencyCode: 'EUR' },
    'Ukraine': { countryCode: 'UA', currencyCode: 'UAH' },
    'Serbia': { countryCode: 'RS', currencyCode: 'RSD' },
    'Montenegro': { countryCode: 'ME', currencyCode: 'EUR' },
    'Kosovo': { countryCode: 'XK', currencyCode: 'EUR' },
    'Croatia': { countryCode: 'HR', currencyCode: 'HRK' },
    'Slovenia': { countryCode: 'SI', currencyCode: 'EUR' },
    'Bosnia and Herzegovina': { countryCode: 'BA', currencyCode: 'BAM' },
    'North Macedonia': { countryCode: 'MK', currencyCode: 'MKD' },
    'Czech Republic': { countryCode: 'CZ', currencyCode: 'CZK' },
    'Slovakia': { countryCode: 'SK', currencyCode: 'EUR' },
    'Liechtenstein': { countryCode: 'LI', currencyCode: 'CHF' },
    'Falkland Islands': { countryCode: 'FK', currencyCode: 'FKP' },
    'Belize': { countryCode: 'BZ', currencyCode: 'BZD' },
    'Guatemala': { countryCode: 'GT', currencyCode: 'GTQ' },
    'El Salvador': { countryCode: 'SV', currencyCode: 'USD' },
    'Honduras': { countryCode: 'HN', currencyCode: 'HNL' },
    'Nicaragua': { countryCode: 'NI', currencyCode: 'NIO' },
    'Costa Rica': { countryCode: 'CR', currencyCode: 'CRC' },
    'Panama': { countryCode: 'PA', currencyCode: 'PAB' },
    'Saint Pierre and Miquelon': { countryCode: 'PM', currencyCode: 'EUR' },
    'Haiti': { countryCode: 'HT', currencyCode: 'HTG' },
    'Guadeloupe': { countryCode: 'GP', currencyCode: 'EUR' },
    'Bolivia': { countryCode: 'BO', currencyCode: 'BOB' },
    'Guyana': { countryCode: 'GY', currencyCode: 'GYD' },
    'Ecuador': { countryCode: 'EC', currencyCode: 'USD' },
    'French Guiana': { countryCode: 'GF', currencyCode: 'EUR' },
    'Paraguay': { countryCode: 'PY', currencyCode: 'PYG' },
    'Martinique': { countryCode: 'MQ', currencyCode: 'EUR' },
    'Suriname': { countryCode: 'SR', currencyCode: 'SRD' },
    'Uruguay': { countryCode: 'UY', currencyCode: 'UYU' },
    'Curaçao and Sint Maarten': { countryCode: 'CW', currencyCode: 'ANG' },
    'Timor-Leste': { countryCode: 'TL', currencyCode: 'USD' },
    'Guam': { countryCode: 'GU', currencyCode: 'USD' },
    'Australian External Territories': { countryCode: 'AU', currencyCode: 'AUD' },
    'Brunei': { countryCode: 'BN', currencyCode: 'BND' },
    'Nauru': { countryCode: 'NR', currencyCode: 'AUD' },
    'Papua New Guinea': { countryCode: 'PG', currencyCode: 'PGK' },
    'Tonga': { countryCode: 'TO', currencyCode: 'TOP' },
    'Solomon Islands': { countryCode: 'SB', currencyCode: 'SBD' },
    'Vanuatu': { countryCode: 'VU', currencyCode: 'VUV' },
    'Fiji': { countryCode: 'FJ', currencyCode: 'FJD' },
    'Palau': { countryCode: 'PW', currencyCode: 'USD' },
    'Wallis and Futuna': { countryCode: 'WF', currencyCode: 'XPF' },
    'Cook Islands': { countryCode: 'CK', currencyCode: 'NZD' },
    'Niue': { countryCode: 'NU', currencyCode: 'NZD' },
    'Samoa': { countryCode: 'WS', currencyCode: 'WST' },
    'Cayman Islands': { countryCode: 'KY', currencyCode: 'KYD' },
    'New Caledonia': { countryCode: 'NC', currencyCode: 'XPF' },
    'Tuvalu': { countryCode: 'TV', currencyCode: 'AUD' },
    'French Polynesia': { countryCode: 'PF', currencyCode: 'XPF' },
    'Micronesia': { countryCode: 'FM', currencyCode: 'USD' },
    'Marshall Islands': { countryCode: 'MH', currencyCode: 'USD' },
    'North Korea': { countryCode: 'KP', currencyCode: 'KPW' },
    'Hong Kong': { countryCode: 'HK', currencyCode: 'HKD' },
    'Macau': { countryCode: 'MO', currencyCode: 'MOP' },
    'Cambodia': { countryCode: 'KH', currencyCode: 'KHR' },
    'Laos': { countryCode: 'LA', currencyCode: 'LAK' },
    'Maldives': { countryCode: 'MV', currencyCode: 'MVR' },
    'Lebanon': { countryCode: 'LB', currencyCode: 'LBP' },
    'Jordan': { countryCode: 'JO', currencyCode: 'JOD' },
    'Syria': { countryCode: 'SY', currencyCode: 'SYP' },
    'Iraq': { countryCode: 'IQ', currencyCode: 'IQD' },
    'Kuwait': { countryCode: 'KW', currencyCode: 'KWD' },
    'Saudi Arabia': { countryCode: 'SA', currencyCode: 'SAR' },
    'Yemen': { countryCode: 'YE', currencyCode: 'YER' },
    'Oman': { countryCode: 'OM', currencyCode: 'OMR' },
    'Palestine': { countryCode: 'PS', currencyCode: 'ILS' },
    'United Arab Emirates': { countryCode: 'AE', currencyCode: 'AED' },
    'Israel': { countryCode: 'IL', currencyCode: 'ILS' },
    'Bahrain': { countryCode: 'BH', currencyCode: 'BHD' },
    'Qatar': { countryCode: 'QA', currencyCode: 'QAR' },
    'Bhutan': { countryCode: 'BT', currencyCode: 'INR' },
    'Mongolia': { countryCode: 'MN', currencyCode: 'MNT' },
    'Nepal': { countryCode: 'NP', currencyCode: 'NPR' },
    'Tajikistan': { countryCode: 'TJ', currencyCode: 'TJS' },
    'Turkmenistan': { countryCode: 'TM', currencyCode: 'TMT' },
    'Azerbaijan': { countryCode: 'AZ', currencyCode: 'AZN' },
    'Georgia': { countryCode: 'GE', currencyCode: 'GEL' },
    'Kyrgyzstan': { countryCode: 'KG', currencyCode: 'KGS' },
    'Uzbekistan': { countryCode: 'UZ', currencyCode: 'UZS' },
  };
